---
name: Slack Notifications
on:
  check_suite:
    types: [completed]

permissions:
  actions: read
  contents: read
  checks: read
  id-token: write

jobs:
  slack-notifications:
    if: >-
      contains(fromJSON('["main", "master"]'), github.event.check_suite.head_branch) || startsWith(github.event.check_suite.head_branch, 'dogfood-') || startsWith(github.event.check_suite.head_branch, 'branch-')
    runs-on: github-ubuntu-latest-s
    steps:
      - name: Send Slack Notification
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: SonarSource/gh-action_slack-notify@9532fdcfa4143ed5da2da7b0e77172abbe24ae33 # v1.0.2
        with:
          slackChannel: squad-sq-platform-build-notification
