name: Unified Dogfooding scans
on:
  schedule:
    # Run the workflow every day at 04:00 UTC
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: github-ubuntu-latest-s
    name: Build and run shadow scans
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-maven@4ef2061ff3c9dc144a66f8a6e480d04d2d79e3bb # v1.3.25
        with:
          artifactory-reader-role: private-reader
          artifactory-deployer-role: qa-deployer
          run-shadow-scans: true

      - name: Run IRIS Analysis
        uses: SonarSource/unified-dogfooding-actions/run-iris@b256ed29572b02741155dad9e6f20735076080e4 # v1
        with:
          primary_project_key: "org.sonarsource.update-center:sonar-update-center"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.update-center:sonar-update-center"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.update-center:sonar-update-center"
          shadow2_platform: "SQC-US"
